#####################################################################
########################    测试环境   ################################
#####################################################################


spring:
###############   数据源配置   ####################
  datasource:
    url: jdbc:mysql://localhost:3306/lemon?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver



###############   Nacos配置信息   ####################
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

    ###############   seata配置信息   ##################
#    alibaba:
#      seata:
#        tx-service-group: order_tx_group # 定义事务组的名称

###############   Sentinel配置信息   ##################
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080


###############   feign配置   ####################
  main:
    allow-bean-definition-overriding: true

  ###############   Redis配置信息   ####################
  redis:
    port: 6379
    host: 127.0.0.1

feign:
  sentinel:
    enabled: true #Sentinel开启对feign的支持


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印sql


##################   自定义配置   ####################
lemon:
  foot:
    limit-time: 86400000 #每个用户最长存储一周的浏览足迹，单位ms
  auth:
    clientId: goods-service
    secret: 1234
    includeFilterPaths: # 拦截的路径
      - /**
    excludeFilterPaths: # 放行的路径
      - /test/**
